export { default as Button } from "./Button/Button";
export { default as Social } from "./Social-icons/Social";
export { default as Team } from "./Team/Team";
export { default as CallUs } from "./Call-us/Call-us";
export { default as OverLay } from "./OverLay/OverLay";
export { default as Stars } from "./Stars/Stars";
export { default as Clients } from "./clients/Clients";
export { default as Pagination } from "./Pagination/Pagination";
export { default as Popup } from "./Popup/Popup";
export { default as ScrollUp } from "./Scroll Up/ScrollUp";
