export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Rooms } from "./Rooms & suites";
export { default as RoomsDetails } from "./Rooms Details/RoomsDetails";
export { default as Resturant } from "./Resturant";
export { default as Spa } from "./Spa/Spa";
export { default as Gallery } from "./Gallery/Gallery";
export { default as News } from "./News/News";
export { default as SinglePost } from "./Single Post/SinglePost";
export { default as Contact } from "./Contact";
export { default as NotFound } from "./NotFound/NotFound";
